- name: Install prerequisites
  apt:
    name: ['postgresql-client', 'curl', 'virtualenv']
    update_cache: yes

- name: Copy aggregate report scripts
  copy:
    dest: "/home/{{ user }}/"
    src: "{{ playbook_dir }}/../perfsuite-aggregate"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Clone QGIS-Server-PerfSuite
  git:
    repo: https://github.com/qgis/QGIS-Server-PerfSuite
    dest: "/home/{{ user }}/QGIS-Server-PerfSuite"
  register: git_repo_perfsuite

- name: Change owner and group of QGIS-Server-PerfSuite
  file:
    dest: "/home/{{ user }}/QGIS-Server-PerfSuite"
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: True
  when: git_repo_perfsuite.changed

- name: Copy ci script
  copy:
    dest: "/home/{{ user }}/perfsuite-ci.sh"
    src: "perfsuite-ci.sh"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Update crontab to periodically run performance tests
  cron:
    name: perfsuite ci
    user: "{{ user }}"
    minute: "0"
    hour: "{{ perfsuite_hour }}"
    job: >
      cd /home/{{ user }} && sh perfsuite-ci.sh > /tmp/perfsuite-ci.log 2>&1

- name: Update crontab to periodically build aggregate performance report
  cron:
    name: perfsuite aggregate report ci
    user: "{{ user }}"
    minute: "0"
    hour: "{{ perfsuite_aggregate_hour }}"
    job: >
      cd /home/{{ user }}/perfsuite-aggregate/ && sh aggregate-ci.sh > /tmp/perfsuite-aggregate-ci.log 2>&1
